#%RAML 1.0 Trait
    headers:
      client_id:
        type: string
        description: Client secret to authenticate to system API
        required: true
      client_secret:
        type: string
        description: Client secret to authenticate to system API
        required: true 