#%RAML 1.0 DataType
type: array
items:
                type: object
                properties:
                  ID?:
                    type: number
                  code:
                    required: true
                    type: string
                  price:
                    required: true
                    type: number
                  departureDate:
                    required: true
                    type: string
                  origin:
                    required: true
                    type: string
                  destination:
                    required: true
                    type: string
                  emptySeats:
                    required: true
                    type: number
                  plane:
                    required: true
                    type: object
                    properties:
                      type: 
                        required: true
                        type: string
                      totalSeats:
                        required: true
                        type: number